on:
  workflow_dispatch:    
  push:
    branches:
      - master
      
name: Docker Image CI - GithubPackes      

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1    
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/edgarrc/ai-deploy:$(date +%s)
        docker push ghcr.io/edgarrc/ai-deploy:latest
